[package]
name = "rustos"
version = "0.1.0"
authors = ["chansuke <chansuke@georepublic.de>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

